<?php
namespace backend\models\validators;
/**
 * Created by PhpStorm.
 * User: suns
 * Date: 2019-03-11
 * Time: 12:10
 */

class LinkageValidator extends \yii\validators\Validator
{
    public $fatherAttribute;
    public $sunAttribute;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function validateAttribute($model, $attribute)
    {
        parent::validateAttribute($model, $attribute); // TODO: Change the autogenerated stub
    }
    public function clientValidateAttribute($model, $attribute, $view)
    {
        return <<<JS
alert('{$attribute}');
JS;
    }

}